FROM  amazoncorretto:17-alpine AS builder

WORKDIR /app

COPY gradlew .
COPY gradle/wrapper gradle/wrapper
COPY build.gradle .
COPY settings.gradle .
COPY src src

RUN ./gradlew bootjar --no-daemon

FROM amazoncorretto:17-alpine AS prod

WORKDIR /app

COPY --from=builder /app/build/libs/RegistroStand-1.0.0.jar app.jar

EXPOSE 8080

# Comando para ejecutar la aplicación

ENTRYPOINT ["java", "-jar", "app.jar"]